- hosts: fe1:fe2:be1:be2:mn:db1:db2:cicd
  tasks:
   - name: Set authorized key took from file
     authorized_key:
       user: public
       state: present
       key: "{{ lookup('file', '~/.ssh/authorized_key.pub') }}"
