- hosts: db1:db2
  tasks:
          - name: run postgresql
            command: "docker run -d --name postgre -v /home/{{ansible_user}}/postgres:/var/lib/postgresql/data -e POSTGRES_PASSWORD=asep -p 5432:5432 postgres"
            become_user: "{{ansible_user}}"

          - name: create database waysgallery 
            command: docker exec -it postgre psql -U postgres -c "CREATE DATABASE waysgallery1;"
            become_user: "{{ansible_user}}"

          - name: create user waysgallery
            command: docker exec -it postgre psql -U postgres -c "CREATE USER backend1 with password 'asep1';"
            become_user: "{{ansible_user}}"

          - name: create access privilege
            command: docker exec -it postgre psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE waysgallery1 to backend1;"
            become_user: "{{ansible_user}}"
