# Mengizinkan akses Docker tanpa root
- hosts: all
  become: yes
  tasks:
    - name: docker permission
      command: chmod 666 /var/run/docker.sock

    - name: docker compose permission
      command: chmod +x /usr/local/bin/docker-compose

    - name: docker system enable
      command: sudo systemctl enable docker
